name: diary_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  change_app_package_name: ^1.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_mobile_ads: ^5.2.0
  intl: ^0.20.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
